### PR TITLE
Add SharedArrayBuffer and Atomics objects

### PR DESCRIPTION
**Pull request by rwalczyna**
Simple handlers has been added

JerryScript-DCO-1.0-Signed-off-by: Rafal Walczyna r.walczyna@samsung.com

I plan to make a container with mutexes for each SharedArrayBuffer. Corresponding mutex will be checked in Atomics methods.

### CODE REVIEW

**Comment by zherczeg** [comment]
How many tests are fixed?

**Comment by rwalczyna** [comment]
'parallel' tests:
No changes: + 1455 | - 1025
This commit: + 1457 | - 1023 
This commit and next, that I'm finishing currently (Atomics.add and Atomics.load): + 1497 | - 983

**Comment by zherczeg** [comment]
I am ok with the patch. Please resolve the conflict.

**Review by zherczeg — APPROVED** [review]
LGTM

**Pull request merged**
